// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: api/protos/v1/playlist/playlist.proto

package playlist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimplePlaylist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumOfMusics  uint64 `protobuf:"varint,2,opt,name=numOfMusics,proto3" json:"numOfMusics,omitempty"`
	CreatedAt    string `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    string `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PlaylistName string `protobuf:"bytes,5,opt,name=playlistName,proto3" json:"playlistName,omitempty"`
}

func (x *SimplePlaylist) Reset() {
	*x = SimplePlaylist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimplePlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplePlaylist) ProtoMessage() {}

func (x *SimplePlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplePlaylist.ProtoReflect.Descriptor instead.
func (*SimplePlaylist) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{0}
}

func (x *SimplePlaylist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimplePlaylist) GetNumOfMusics() uint64 {
	if x != nil {
		return x.NumOfMusics
	}
	return 0
}

func (x *SimplePlaylist) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SimplePlaylist) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SimplePlaylist) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

type GetMyPlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyPlaylistReq) Reset() {
	*x = GetMyPlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyPlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPlaylistReq) ProtoMessage() {}

func (x *GetMyPlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPlaylistReq.ProtoReflect.Descriptor instead.
func (*GetMyPlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{1}
}

type GetMyPlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd     string            `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg    string            `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
	MyPlaylist []*SimplePlaylist `protobuf:"bytes,3,rep,name=myPlaylist,proto3" json:"myPlaylist,omitempty"`
}

func (x *GetMyPlaylistRes) Reset() {
	*x = GetMyPlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyPlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyPlaylistRes) ProtoMessage() {}

func (x *GetMyPlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyPlaylistRes.ProtoReflect.Descriptor instead.
func (*GetMyPlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyPlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *GetMyPlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

func (x *GetMyPlaylistRes) GetMyPlaylist() []*SimplePlaylist {
	if x != nil {
		return x.MyPlaylist
	}
	return nil
}

type Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MusicId     string `protobuf:"bytes,1,opt,name=musicId,proto3" json:"musicId,omitempty"`
	TrackNumber uint64 `protobuf:"varint,2,opt,name=trackNumber,proto3" json:"trackNumber,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist      string `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	Album       string `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	Genre       string `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	AlbumImg    string `protobuf:"bytes,7,opt,name=albumImg,proto3" json:"albumImg,omitempty"`
	MusicUrl    string `protobuf:"bytes,8,opt,name=musicUrl,proto3" json:"musicUrl,omitempty"`
	IsTitle     bool   `protobuf:"varint,9,opt,name=isTitle,proto3" json:"isTitle,omitempty"`
}

func (x *Music) Reset() {
	*x = Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{3}
}

func (x *Music) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

func (x *Music) GetTrackNumber() uint64 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

func (x *Music) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Music) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Music) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Music) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Music) GetAlbumImg() string {
	if x != nil {
		return x.AlbumImg
	}
	return ""
}

func (x *Music) GetMusicUrl() string {
	if x != nil {
		return x.MusicUrl
	}
	return ""
}

func (x *Music) GetIsTitle() bool {
	if x != nil {
		return x.IsTitle
	}
	return false
}

type SpecificPlaylist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt    string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    string   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PlaylistName string   `protobuf:"bytes,4,opt,name=playlistName,proto3" json:"playlistName,omitempty"`
	NumOfLike    uint64   `protobuf:"varint,5,opt,name=numOfLike,proto3" json:"numOfLike,omitempty"`
	MusicList    []*Music `protobuf:"bytes,6,rep,name=musicList,proto3" json:"musicList,omitempty"`
}

func (x *SpecificPlaylist) Reset() {
	*x = SpecificPlaylist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecificPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificPlaylist) ProtoMessage() {}

func (x *SpecificPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificPlaylist.ProtoReflect.Descriptor instead.
func (*SpecificPlaylist) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{4}
}

func (x *SpecificPlaylist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpecificPlaylist) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SpecificPlaylist) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SpecificPlaylist) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *SpecificPlaylist) GetNumOfLike() uint64 {
	if x != nil {
		return x.NumOfLike
	}
	return 0
}

func (x *SpecificPlaylist) GetMusicList() []*Music {
	if x != nil {
		return x.MusicList
	}
	return nil
}

type GetSpecificPlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId string `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
}

func (x *GetSpecificPlaylistReq) Reset() {
	*x = GetSpecificPlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpecificPlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecificPlaylistReq) ProtoMessage() {}

func (x *GetSpecificPlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecificPlaylistReq.ProtoReflect.Descriptor instead.
func (*GetSpecificPlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{5}
}

func (x *GetSpecificPlaylistReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type GetSpecificPlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd   string            `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg  string            `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
	Playlist *SpecificPlaylist `protobuf:"bytes,3,opt,name=playlist,proto3" json:"playlist,omitempty"`
}

func (x *GetSpecificPlaylistRes) Reset() {
	*x = GetSpecificPlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpecificPlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecificPlaylistRes) ProtoMessage() {}

func (x *GetSpecificPlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecificPlaylistRes.ProtoReflect.Descriptor instead.
func (*GetSpecificPlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpecificPlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *GetSpecificPlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

func (x *GetSpecificPlaylistRes) GetPlaylist() *SpecificPlaylist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

type CreateNewPlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistName string `protobuf:"bytes,1,opt,name=playlistName,proto3" json:"playlistName,omitempty"`
}

func (x *CreateNewPlaylistReq) Reset() {
	*x = CreateNewPlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewPlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewPlaylistReq) ProtoMessage() {}

func (x *CreateNewPlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewPlaylistReq.ProtoReflect.Descriptor instead.
func (*CreateNewPlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNewPlaylistReq) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

type CreateNewPlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *CreateNewPlaylistRes) Reset() {
	*x = CreateNewPlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewPlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewPlaylistRes) ProtoMessage() {}

func (x *CreateNewPlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewPlaylistRes.ProtoReflect.Descriptor instead.
func (*CreateNewPlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNewPlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *CreateNewPlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

type UpdatePlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistName string `protobuf:"bytes,1,opt,name=playlistName,proto3" json:"playlistName,omitempty"`
	PlaylistId   string `protobuf:"bytes,2,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
}

func (x *UpdatePlaylistReq) Reset() {
	*x = UpdatePlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistReq) ProtoMessage() {}

func (x *UpdatePlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistReq.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePlaylistReq) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *UpdatePlaylistReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type UpdatePlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *UpdatePlaylistRes) Reset() {
	*x = UpdatePlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlaylistRes) ProtoMessage() {}

func (x *UpdatePlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlaylistRes.ProtoReflect.Descriptor instead.
func (*UpdatePlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *UpdatePlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

type AddNewMusicInPlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId  string   `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	MusicIdList []string `protobuf:"bytes,2,rep,name=musicIdList,proto3" json:"musicIdList,omitempty"`
}

func (x *AddNewMusicInPlaylistReq) Reset() {
	*x = AddNewMusicInPlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewMusicInPlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewMusicInPlaylistReq) ProtoMessage() {}

func (x *AddNewMusicInPlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewMusicInPlaylistReq.ProtoReflect.Descriptor instead.
func (*AddNewMusicInPlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{11}
}

func (x *AddNewMusicInPlaylistReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *AddNewMusicInPlaylistReq) GetMusicIdList() []string {
	if x != nil {
		return x.MusicIdList
	}
	return nil
}

type AddNewMusicInPlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *AddNewMusicInPlaylistRes) Reset() {
	*x = AddNewMusicInPlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewMusicInPlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewMusicInPlaylistRes) ProtoMessage() {}

func (x *AddNewMusicInPlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewMusicInPlaylistRes.ProtoReflect.Descriptor instead.
func (*AddNewMusicInPlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{12}
}

func (x *AddNewMusicInPlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *AddNewMusicInPlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

type RemoveMusicInPlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId  string   `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
	MusicIdList []string `protobuf:"bytes,2,rep,name=musicIdList,proto3" json:"musicIdList,omitempty"`
}

func (x *RemoveMusicInPlaylistReq) Reset() {
	*x = RemoveMusicInPlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMusicInPlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMusicInPlaylistReq) ProtoMessage() {}

func (x *RemoveMusicInPlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMusicInPlaylistReq.ProtoReflect.Descriptor instead.
func (*RemoveMusicInPlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMusicInPlaylistReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *RemoveMusicInPlaylistReq) GetMusicIdList() []string {
	if x != nil {
		return x.MusicIdList
	}
	return nil
}

type RemoveMusicInPlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *RemoveMusicInPlaylistRes) Reset() {
	*x = RemoveMusicInPlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMusicInPlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMusicInPlaylistRes) ProtoMessage() {}

func (x *RemoveMusicInPlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMusicInPlaylistRes.ProtoReflect.Descriptor instead.
func (*RemoveMusicInPlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveMusicInPlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *RemoveMusicInPlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

type LikePlaylistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaylistId string `protobuf:"bytes,1,opt,name=playlistId,proto3" json:"playlistId,omitempty"`
}

func (x *LikePlaylistReq) Reset() {
	*x = LikePlaylistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikePlaylistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePlaylistReq) ProtoMessage() {}

func (x *LikePlaylistReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePlaylistReq.ProtoReflect.Descriptor instead.
func (*LikePlaylistReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{15}
}

func (x *LikePlaylistReq) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

type LikePlaylistRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *LikePlaylistRes) Reset() {
	*x = LikePlaylistRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikePlaylistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePlaylistRes) ProtoMessage() {}

func (x *LikePlaylistRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_playlist_playlist_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePlaylistRes.ProtoReflect.Descriptor instead.
func (*LikePlaylistRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_playlist_playlist_proto_rawDescGZIP(), []int{16}
}

func (x *LikePlaylistRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *LikePlaylistRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

var File_api_protos_v1_playlist_playlist_proto protoreflect.FileDescriptor

var file_api_protos_v1_playlist_playlist_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70,
	0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x22, 0x87, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x50, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74,
	0x43, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x41, 0x0a, 0x0a, 0x6d, 0x79,
	0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x0a, 0x6d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xef, 0x01,
	0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6d, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0xd8, 0x01, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x4c, 0x69, 0x6b,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x4c, 0x69,
	0x6b, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52,
	0x09, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x3f, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50,
	0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x57, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49,
	0x64, 0x22, 0x45, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x5c, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x73,
	0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x6c,
	0x74, 0x4d, 0x73, 0x67, 0x22, 0x5c, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75,
	0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x4c, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67,
	0x22, 0x31, 0x0a, 0x0f, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x32, 0xea, 0x05, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x29, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63,
	0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e,
	0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x73, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63,
	0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x2b, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x76,
	0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x50, 0x6c,
	0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0c, 0x4c,
	0x69, 0x6b, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x61, 0x72, 0x6b, 0x2d, 0x4b, 0x77, 0x6f, 0x6e, 0x73, 0x6f, 0x6f,
	0x2f, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61,
	0x79, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protos_v1_playlist_playlist_proto_rawDescOnce sync.Once
	file_api_protos_v1_playlist_playlist_proto_rawDescData = file_api_protos_v1_playlist_playlist_proto_rawDesc
)

func file_api_protos_v1_playlist_playlist_proto_rawDescGZIP() []byte {
	file_api_protos_v1_playlist_playlist_proto_rawDescOnce.Do(func() {
		file_api_protos_v1_playlist_playlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protos_v1_playlist_playlist_proto_rawDescData)
	})
	return file_api_protos_v1_playlist_playlist_proto_rawDescData
}

var file_api_protos_v1_playlist_playlist_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_protos_v1_playlist_playlist_proto_goTypes = []interface{}{
	(*SimplePlaylist)(nil),           // 0: v1.playlist_proto.SimplePlaylist
	(*GetMyPlaylistReq)(nil),         // 1: v1.playlist_proto.GetMyPlaylistReq
	(*GetMyPlaylistRes)(nil),         // 2: v1.playlist_proto.GetMyPlaylistRes
	(*Music)(nil),                    // 3: v1.playlist_proto.Music
	(*SpecificPlaylist)(nil),         // 4: v1.playlist_proto.SpecificPlaylist
	(*GetSpecificPlaylistReq)(nil),   // 5: v1.playlist_proto.GetSpecificPlaylistReq
	(*GetSpecificPlaylistRes)(nil),   // 6: v1.playlist_proto.GetSpecificPlaylistRes
	(*CreateNewPlaylistReq)(nil),     // 7: v1.playlist_proto.CreateNewPlaylistReq
	(*CreateNewPlaylistRes)(nil),     // 8: v1.playlist_proto.CreateNewPlaylistRes
	(*UpdatePlaylistReq)(nil),        // 9: v1.playlist_proto.UpdatePlaylistReq
	(*UpdatePlaylistRes)(nil),        // 10: v1.playlist_proto.UpdatePlaylistRes
	(*AddNewMusicInPlaylistReq)(nil), // 11: v1.playlist_proto.AddNewMusicInPlaylistReq
	(*AddNewMusicInPlaylistRes)(nil), // 12: v1.playlist_proto.AddNewMusicInPlaylistRes
	(*RemoveMusicInPlaylistReq)(nil), // 13: v1.playlist_proto.RemoveMusicInPlaylistReq
	(*RemoveMusicInPlaylistRes)(nil), // 14: v1.playlist_proto.RemoveMusicInPlaylistRes
	(*LikePlaylistReq)(nil),          // 15: v1.playlist_proto.LikePlaylistReq
	(*LikePlaylistRes)(nil),          // 16: v1.playlist_proto.LikePlaylistRes
}
var file_api_protos_v1_playlist_playlist_proto_depIdxs = []int32{
	0,  // 0: v1.playlist_proto.GetMyPlaylistRes.myPlaylist:type_name -> v1.playlist_proto.SimplePlaylist
	3,  // 1: v1.playlist_proto.SpecificPlaylist.musicList:type_name -> v1.playlist_proto.Music
	4,  // 2: v1.playlist_proto.GetSpecificPlaylistRes.playlist:type_name -> v1.playlist_proto.SpecificPlaylist
	1,  // 3: v1.playlist_proto.PlaylistService.GetMyPlaylist:input_type -> v1.playlist_proto.GetMyPlaylistReq
	5,  // 4: v1.playlist_proto.PlaylistService.GetSpecificPlaylist:input_type -> v1.playlist_proto.GetSpecificPlaylistReq
	7,  // 5: v1.playlist_proto.PlaylistService.CreateNewPlaylist:input_type -> v1.playlist_proto.CreateNewPlaylistReq
	9,  // 6: v1.playlist_proto.PlaylistService.UpdatePlaylist:input_type -> v1.playlist_proto.UpdatePlaylistReq
	11, // 7: v1.playlist_proto.PlaylistService.AddNewMusicInPlaylist:input_type -> v1.playlist_proto.AddNewMusicInPlaylistReq
	13, // 8: v1.playlist_proto.PlaylistService.RemoveMusicInPlaylist:input_type -> v1.playlist_proto.RemoveMusicInPlaylistReq
	15, // 9: v1.playlist_proto.PlaylistService.LikePlaylist:input_type -> v1.playlist_proto.LikePlaylistReq
	2,  // 10: v1.playlist_proto.PlaylistService.GetMyPlaylist:output_type -> v1.playlist_proto.GetMyPlaylistRes
	6,  // 11: v1.playlist_proto.PlaylistService.GetSpecificPlaylist:output_type -> v1.playlist_proto.GetSpecificPlaylistRes
	8,  // 12: v1.playlist_proto.PlaylistService.CreateNewPlaylist:output_type -> v1.playlist_proto.CreateNewPlaylistRes
	10, // 13: v1.playlist_proto.PlaylistService.UpdatePlaylist:output_type -> v1.playlist_proto.UpdatePlaylistRes
	12, // 14: v1.playlist_proto.PlaylistService.AddNewMusicInPlaylist:output_type -> v1.playlist_proto.AddNewMusicInPlaylistRes
	14, // 15: v1.playlist_proto.PlaylistService.RemoveMusicInPlaylist:output_type -> v1.playlist_proto.RemoveMusicInPlaylistRes
	16, // 16: v1.playlist_proto.PlaylistService.LikePlaylist:output_type -> v1.playlist_proto.LikePlaylistRes
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_protos_v1_playlist_playlist_proto_init() }
func file_api_protos_v1_playlist_playlist_proto_init() {
	if File_api_protos_v1_playlist_playlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protos_v1_playlist_playlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimplePlaylist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyPlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyPlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecificPlaylist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpecificPlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpecificPlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewPlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewPlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewMusicInPlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewMusicInPlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMusicInPlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMusicInPlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikePlaylistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_playlist_playlist_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikePlaylistRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protos_v1_playlist_playlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_v1_playlist_playlist_proto_goTypes,
		DependencyIndexes: file_api_protos_v1_playlist_playlist_proto_depIdxs,
		MessageInfos:      file_api_protos_v1_playlist_playlist_proto_msgTypes,
	}.Build()
	File_api_protos_v1_playlist_playlist_proto = out.File
	file_api_protos_v1_playlist_playlist_proto_rawDesc = nil
	file_api_protos_v1_playlist_playlist_proto_goTypes = nil
	file_api_protos_v1_playlist_playlist_proto_depIdxs = nil
}
