package models

import (
	"reflect"
	"time"
)

type baseType struct {
	ID        uint      `db:"id int generated by default as identity primary key"`
	CreatedAt time.Time `db:"created_at timestamp not null default now()"`
	UpdatedAt time.Time `db:"updated_at timestamp not null default now()"`
	DeletedAt time.Time `db:"deleted_at timestamp default null"`
}

//BaseType의 create table시 사용할 컬럼 옵션 리턴
func getCreatedTableColumn() []string {
	b := baseType{}

	id, _ := reflect.TypeOf(b).FieldByName("ID")
	createdAt, _ := reflect.TypeOf(b).FieldByName("CreatedAt")
	updatedAt, _ := reflect.TypeOf(b).FieldByName("UpdatedAt")
	deletedAt, _ := reflect.TypeOf(b).FieldByName("DeletedAt")

	return []string{
		id.Tag.Get("db"),
		createdAt.Tag.Get("db"),
		updatedAt.Tag.Get("db"),
		deletedAt.Tag.Get("db"),
	}
}
