package models

import (
	"time"

	getTag "github.com/Park-Kwonsoo/moving-server/pkg/get-struct-info"
)

type baseType struct {
	ID        uint      `db:"id int generated by default as identity primary key"`
	CreatedAt time.Time `db:"created_at timestamp not null default now()"`
	UpdatedAt time.Time `db:"updated_at timestamp not null default now()"`
	DeletedAt time.Time `db:"deleted_at timestamp default null"`
}

//BaseType의 create table시 사용할 컬럼 옵션 리턴
func getCreatedTableColumn() []string {

	column := make([]string, 0)
	column = append(column, getTag.GetStructInfoByTag("db", &baseType{})...)

	return column
}
