// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: api/protos/v1/music/music.proto

package music

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Music struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MusicId       string `protobuf:"bytes,1,opt,name=musicId,proto3" json:"musicId,omitempty"`
	TrackNumber   uint64 `protobuf:"varint,2,opt,name=trackNumber,proto3" json:"trackNumber,omitempty"`
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	Genre         string `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	AlbumCoverUrl string `protobuf:"bytes,7,opt,name=albumCoverUrl,proto3" json:"albumCoverUrl,omitempty"`
	MusicUrl      string `protobuf:"bytes,8,opt,name=musicUrl,proto3" json:"musicUrl,omitempty"`
	IsTitle       bool   `protobuf:"varint,9,opt,name=isTitle,proto3" json:"isTitle,omitempty"`
}

func (x *Music) Reset() {
	*x = Music{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Music) ProtoMessage() {}

func (x *Music) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Music.ProtoReflect.Descriptor instead.
func (*Music) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{0}
}

func (x *Music) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

func (x *Music) GetTrackNumber() uint64 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

func (x *Music) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Music) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Music) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Music) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Music) GetAlbumCoverUrl() string {
	if x != nil {
		return x.AlbumCoverUrl
	}
	return ""
}

func (x *Music) GetMusicUrl() string {
	if x != nil {
		return x.MusicUrl
	}
	return ""
}

func (x *Music) GetIsTitle() bool {
	if x != nil {
		return x.IsTitle
	}
	return false
}

type GetMusicDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MusicId string `protobuf:"bytes,1,opt,name=musicId,proto3" json:"musicId,omitempty"`
}

func (x *GetMusicDetailReq) Reset() {
	*x = GetMusicDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicDetailReq) ProtoMessage() {}

func (x *GetMusicDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicDetailReq.ProtoReflect.Descriptor instead.
func (*GetMusicDetailReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{1}
}

func (x *GetMusicDetailReq) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

type GetMusicDetailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
	Music   *Music `protobuf:"bytes,3,opt,name=music,proto3" json:"music,omitempty"`
}

func (x *GetMusicDetailRes) Reset() {
	*x = GetMusicDetailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicDetailRes) ProtoMessage() {}

func (x *GetMusicDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicDetailRes.ProtoReflect.Descriptor instead.
func (*GetMusicDetailRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{2}
}

func (x *GetMusicDetailRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *GetMusicDetailRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

func (x *GetMusicDetailRes) GetMusic() *Music {
	if x != nil {
		return x.Music
	}
	return nil
}

type GetMusicByKeywordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *GetMusicByKeywordReq) Reset() {
	*x = GetMusicByKeywordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicByKeywordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicByKeywordReq) ProtoMessage() {}

func (x *GetMusicByKeywordReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicByKeywordReq.ProtoReflect.Descriptor instead.
func (*GetMusicByKeywordReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{3}
}

func (x *GetMusicByKeywordReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type GetMusicByKeywordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd       string   `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg      string   `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
	SearchResult []*Music `protobuf:"bytes,3,rep,name=searchResult,proto3" json:"searchResult,omitempty"`
}

func (x *GetMusicByKeywordRes) Reset() {
	*x = GetMusicByKeywordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMusicByKeywordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMusicByKeywordRes) ProtoMessage() {}

func (x *GetMusicByKeywordRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMusicByKeywordRes.ProtoReflect.Descriptor instead.
func (*GetMusicByKeywordRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{4}
}

func (x *GetMusicByKeywordRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *GetMusicByKeywordRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

func (x *GetMusicByKeywordRes) GetSearchResult() []*Music {
	if x != nil {
		return x.SearchResult
	}
	return nil
}

type AddNewMusicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Music       []byte `protobuf:"bytes,1,opt,name=music,proto3" json:"music,omitempty"`
	AlbumImg    []byte `protobuf:"bytes,2,opt,name=albumImg,proto3" json:"albumImg,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Artist      string `protobuf:"bytes,4,opt,name=artist,proto3" json:"artist,omitempty"`
	Album       string `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	Genre       string `protobuf:"bytes,6,opt,name=genre,proto3" json:"genre,omitempty"`
	IsTitle     bool   `protobuf:"varint,7,opt,name=isTitle,proto3" json:"isTitle,omitempty"`
	TrackNumber uint64 `protobuf:"varint,8,opt,name=trackNumber,proto3" json:"trackNumber,omitempty"`
}

func (x *AddNewMusicReq) Reset() {
	*x = AddNewMusicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewMusicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewMusicReq) ProtoMessage() {}

func (x *AddNewMusicReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewMusicReq.ProtoReflect.Descriptor instead.
func (*AddNewMusicReq) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{5}
}

func (x *AddNewMusicReq) GetMusic() []byte {
	if x != nil {
		return x.Music
	}
	return nil
}

func (x *AddNewMusicReq) GetAlbumImg() []byte {
	if x != nil {
		return x.AlbumImg
	}
	return nil
}

func (x *AddNewMusicReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddNewMusicReq) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *AddNewMusicReq) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *AddNewMusicReq) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *AddNewMusicReq) GetIsTitle() bool {
	if x != nil {
		return x.IsTitle
	}
	return false
}

func (x *AddNewMusicReq) GetTrackNumber() uint64 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

type AddNewMusicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RsltCd  string `protobuf:"bytes,1,opt,name=rsltCd,proto3" json:"rsltCd,omitempty"`
	RsltMsg string `protobuf:"bytes,2,opt,name=rsltMsg,proto3" json:"rsltMsg,omitempty"`
}

func (x *AddNewMusicRes) Reset() {
	*x = AddNewMusicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protos_v1_music_music_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewMusicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewMusicRes) ProtoMessage() {}

func (x *AddNewMusicRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_v1_music_music_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewMusicRes.ProtoReflect.Descriptor instead.
func (*AddNewMusicRes) Descriptor() ([]byte, []int) {
	return file_api_protos_v1_music_music_proto_rawDescGZIP(), []int{6}
}

func (x *AddNewMusicRes) GetRsltCd() string {
	if x != nil {
		return x.RsltCd
	}
	return ""
}

func (x *AddNewMusicRes) GetRsltMsg() string {
	if x != nil {
		return x.RsltMsg
	}
	return ""
}

var File_api_protos_v1_music_music_proto protoreflect.FileDescriptor

var file_api_protos_v1_music_music_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf9, 0x01, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75,
	0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55,
	0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x55, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x2d, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x73, 0x6c,
	0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74,
	0x4d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63,
	0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x42, 0x79, 0x4b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x42,
	0x79, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x73, 0x6c, 0x74, 0x43, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c,
	0x74, 0x43, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x39, 0x0a,
	0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xd8, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x75, 0x73, 0x69,
	0x63, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6d, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6c, 0x62, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x73, 0x6c, 0x74, 0x43, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x73, 0x6c, 0x74, 0x4d, 0x73, 0x67, 0x32, 0x9e, 0x02, 0x0a, 0x0c, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x61, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x42, 0x79,
	0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x24, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x4d, 0x75, 0x73, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x61, 0x72, 0x6b, 0x2d, 0x4b, 0x77, 0x6f, 0x6e,
	0x73, 0x6f, 0x6f, 0x2f, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protos_v1_music_music_proto_rawDescOnce sync.Once
	file_api_protos_v1_music_music_proto_rawDescData = file_api_protos_v1_music_music_proto_rawDesc
)

func file_api_protos_v1_music_music_proto_rawDescGZIP() []byte {
	file_api_protos_v1_music_music_proto_rawDescOnce.Do(func() {
		file_api_protos_v1_music_music_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protos_v1_music_music_proto_rawDescData)
	})
	return file_api_protos_v1_music_music_proto_rawDescData
}

var file_api_protos_v1_music_music_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_protos_v1_music_music_proto_goTypes = []interface{}{
	(*Music)(nil),                // 0: v1.music_proto.Music
	(*GetMusicDetailReq)(nil),    // 1: v1.music_proto.GetMusicDetailReq
	(*GetMusicDetailRes)(nil),    // 2: v1.music_proto.GetMusicDetailRes
	(*GetMusicByKeywordReq)(nil), // 3: v1.music_proto.GetMusicByKeywordReq
	(*GetMusicByKeywordRes)(nil), // 4: v1.music_proto.GetMusicByKeywordRes
	(*AddNewMusicReq)(nil),       // 5: v1.music_proto.AddNewMusicReq
	(*AddNewMusicRes)(nil),       // 6: v1.music_proto.AddNewMusicRes
}
var file_api_protos_v1_music_music_proto_depIdxs = []int32{
	0, // 0: v1.music_proto.GetMusicDetailRes.music:type_name -> v1.music_proto.Music
	0, // 1: v1.music_proto.GetMusicByKeywordRes.searchResult:type_name -> v1.music_proto.Music
	1, // 2: v1.music_proto.MusicService.GetMusicDetail:input_type -> v1.music_proto.GetMusicDetailReq
	3, // 3: v1.music_proto.MusicService.GetMusicByKeyword:input_type -> v1.music_proto.GetMusicByKeywordReq
	5, // 4: v1.music_proto.MusicService.AddNewMusic:input_type -> v1.music_proto.AddNewMusicReq
	2, // 5: v1.music_proto.MusicService.GetMusicDetail:output_type -> v1.music_proto.GetMusicDetailRes
	4, // 6: v1.music_proto.MusicService.GetMusicByKeyword:output_type -> v1.music_proto.GetMusicByKeywordRes
	6, // 7: v1.music_proto.MusicService.AddNewMusic:output_type -> v1.music_proto.AddNewMusicRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protos_v1_music_music_proto_init() }
func file_api_protos_v1_music_music_proto_init() {
	if File_api_protos_v1_music_music_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protos_v1_music_music_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Music); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicDetailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicByKeywordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMusicByKeywordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewMusicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protos_v1_music_music_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewMusicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protos_v1_music_music_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_v1_music_music_proto_goTypes,
		DependencyIndexes: file_api_protos_v1_music_music_proto_depIdxs,
		MessageInfos:      file_api_protos_v1_music_music_proto_msgTypes,
	}.Build()
	File_api_protos_v1_music_music_proto = out.File
	file_api_protos_v1_music_music_proto_rawDesc = nil
	file_api_protos_v1_music_music_proto_goTypes = nil
	file_api_protos_v1_music_music_proto_depIdxs = nil
}
